export function sampleLeads() {
  return {
    result: [
      {
        id: "101",
        TITLE: "ACME Corp - Inbound",
        NAME: "John",
        LAST_NAME: "Doe",
        STATUS_ID: "IN_PROCESS",
        SOURCE_ID: "WEB",
        PHONE: [{ value: "+1 555-0101", type: "WORK" }],
        EMAIL: [{ value: "john.doe@example.com", type: "WORK" }],
      },
      {
        id: "102",
        TITLE: "Globex - Website form",
        NAME: "Jane",
        LAST_NAME: "Smith",
        STATUS_ID: "NEW",
        SOURCE_ID: "WEBFORM",
        PHONE: [{ value: "+1 555-0202", type: "MOBILE" }],
        EMAIL: [{ value: "jane.smith@globex.com", type: "WORK" }],
      },
      {
        id: "103",
        TITLE: "Initech - Referral",
        NAME: "Peter",
        LAST_NAME: "Gibbons",
        STATUS_ID: "PROCESSED",
        SOURCE_ID: "RECOMMENDATION",
        PHONE: [{ value: "+1 555-0303", type: "WORK" }],
        EMAIL: [{ value: "peter@initech.io", type: "WORK" }],
      },
      {
        id: "104",
        TITLE: "Umbrella - Call",
        NAME: "Alice",
        LAST_NAME: "Wong",
        STATUS_ID: "CONVERTED",
        SOURCE_ID: "CALL",
        PHONE: [{ value: "+1 555-0404", type: "WORK" }],
        EMAIL: [{ value: "alice.wong@umbrella.org", type: "WORK" }],
      },
    ],
  }
}

export function sampleTasks() {
  return [
    {
      id: "434",
      parentId: "0",
      title: "test task 1",
      description: "",
      mark: null,
      priority: "1",
      multitask: "N",
      notViewed: "N",
      replicate: "N",
      stageId: "0",
      createdBy: "1",
      createdDate: "2024-11-22T13:58:17+02:00",
      responsibleId: "1",
      changedBy: "1",
      changedDate: "2024-11-26T13:43:28+02:00",
      statusChangedBy: "1",
      closedBy: "0",
      closedDate: null,
      activityDate: "2024-11-22T13:58:17+02:00",
      dateStart: "2024-11-26T13:43:28+02:00",
      deadline: null,
      startDatePlan: null,
      endDatePlan: null,
      guid: "{8a261464-64eb-4d04-827b-37ded5433e85}",
      xmlId: null,
      commentsCount: null,
      serviceCommentsCount: null,
      allowChangeDeadline: "Y",
      allowTimeTracking: "N",
      taskControl: "Y",
      addInReport: "N",
      forkedByTemplateId: null,
      timeEstimate: "0",
      timeSpentInLogs: null,
      matchWorkTime: "N",
      forumTopicId: null,
      forumId: null,
      siteId: "s1",
      subordinate: "N",
      exchangeModified: null,
      exchangeId: null,
      outlookVersion: "2",
      viewedDate: "2024-11-26T13:40:45+02:00",
      sorting: null,
      durationFact: null,
      isMuted: "N",
      isPinned: "N",
      isPinnedInGroup: "N",
      flowId: null,
      descriptionInBbcode: "Y",
      status: "3",
      statusChangedDate: "2024-11-26T13:43:28+02:00",
      durationPlan: null,
      durationType: "days",
      favorite: "N",
      groupId: "0",
      auditors: [],
      accomplices: [],
      newCommentsCount: 0,
      group: [],
      creator: {
        id: "1",
        name: "Admin Adminov",
        link: "/company/personal/user/1/",
        icon: "/bitrix/images/tasks/default_avatar.png",
        workPosition: "Chief",
      },
      responsible: {
        id: "1",
        name: "Admin Adminov",
        link: "/company/personal/user/1/",
        icon: "/bitrix/images/tasks/default_avatar.png",
        workPosition: "Chief",
      },
      accomplicesData: [],
      auditorsData: [],
      subStatus: "3",
    },
    {
      id: "435",
      parentId: "0",
      title: "Follow up call",
      description: "Call the client and confirm requirements",
      mark: null,
      priority: "2",
      multitask: "N",
      notViewed: "N",
      replicate: "N",
      stageId: "0",
      createdBy: "1",
      createdDate: "2024-11-25T09:15:00+02:00",
      responsibleId: "6",
      changedBy: "6",
      changedDate: "2024-11-26T10:20:00+02:00",
      statusChangedBy: "6",
      closedBy: "0",
      closedDate: null,
      activityDate: "2024-11-25T09:15:00+02:00",
      dateStart: "2024-11-26T10:20:00+02:00",
      deadline: "2024-11-30T17:00:00+02:00",
      startDatePlan: null,
      endDatePlan: null,
      guid: "{00000000-0000-0000-0000-000000000001}",
      xmlId: null,
      commentsCount: 1,
      serviceCommentsCount: 0,
      allowChangeDeadline: "Y",
      allowTimeTracking: "N",
      taskControl: "Y",
      addInReport: "N",
      forkedByTemplateId: null,
      timeEstimate: "0",
      timeSpentInLogs: null,
      matchWorkTime: "N",
      forumTopicId: null,
      forumId: null,
      siteId: "s1",
      subordinate: "N",
      exchangeModified: null,
      exchangeId: null,
      outlookVersion: "2",
      viewedDate: null,
      sorting: null,
      durationFact: null,
      isMuted: "N",
      isPinned: "N",
      isPinnedInGroup: "N",
      flowId: null,
      descriptionInBbcode: "N",
      status: "2",
      statusChangedDate: "2024-11-26T10:20:00+02:00",
      durationPlan: null,
      durationType: "days",
      favorite: "N",
      groupId: "0",
      auditors: [],
      accomplices: [],
      newCommentsCount: 0,
      group: [],
      creator: {
        id: "6",
        name: "User Example",
        link: "/company/personal/user/6/",
        icon: "/bitrix/images/tasks/default_avatar.png",
        workPosition: "Sales",
      },
      responsible: {
        id: "6",
        name: "User Example",
        link: "/company/personal/user/6/",
        icon: "/bitrix/images/tasks/default_avatar.png",
        workPosition: "Sales",
      },
      accomplicesData: [],
      auditorsData: [],
      subStatus: "2",
    },
  ]
}

export function sampleDeals() {
  return [
    {
      ID: "37",
      TITLE: "[A] Deal",
      TYPE_ID: "COMPLEX",
      CATEGORY_ID: "1",
      STAGE_ID: "C1:NEW",
      OPPORTUNITY: "19999.99",
      IS_MANUAL_OPPORTUNITY: "Y",
      ASSIGNED_BY_ID: "1",
      DATE_CREATE: "2024-09-02T18:37:18+02:00",
    },
    {
      ID: "38",
      TITLE: "[A] Deal",
      TYPE_ID: "COMPLEX",
      CATEGORY_ID: "1",
      STAGE_ID: "C1:NEW",
      OPPORTUNITY: "20000.00",
      IS_MANUAL_OPPORTUNITY: "Y",
      ASSIGNED_BY_ID: "6",
      DATE_CREATE: "2024-09-02T18:37:38+02:00",
    },
    {
      ID: "39",
      TITLE: "[B] Sale",
      TYPE_ID: "COMPLEX",
      CATEGORY_ID: "1",
      STAGE_ID: "C1:NEW",
      OPPORTUNITY: "12500.00",
      IS_MANUAL_OPPORTUNITY: "Y",
      ASSIGNED_BY_ID: "1",
      DATE_CREATE: "2024-04-09T23:11:01+02:00",
    },
    {
      ID: "40",
      TITLE: "[B] Deal",
      TYPE_ID: "COMPLEX",
      CATEGORY_ID: "1",
      STAGE_ID: "C1:NEW",
      OPPORTUNITY: "13500.00",
      IS_MANUAL_OPPORTUNITY: "Y",
      ASSIGNED_BY_ID: "6",
      DATE_CREATE: "2024-08-08T19:00:14+02:00",
    },
    {
      ID: "41",
      TITLE: "[C] Deal",
      TYPE_ID: "COMPLEX",
      CATEGORY_ID: "1",
      STAGE_ID: "C1:NEW",
      OPPORTUNITY: "11500.00",
      IS_MANUAL_OPPORTUNITY: "Y",
      ASSIGNED_BY_ID: "6",
      DATE_CREATE: "2024-05-08T09:38:23+02:00",
    },
    {
      ID: "42",
      TITLE: "[D] Deal",
      TYPE_ID: "COMPLEX",
      CATEGORY_ID: "1",
      STAGE_ID: "C1:NEW",
      OPPORTUNITY: "18500.00",
      IS_MANUAL_OPPORTUNITY: "Y",
      ASSIGNED_BY_ID: "6",
      DATE_CREATE: "2024-07-02T15:38:32+02:00",
    },
  ]
}